/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * SQL federation engine. Configure once via {@link fromYaml} or
 * {@link fromPath}, then call {@link query} (async) or {@link querySync}.
 */
export declare class Engine {
  /** Build an engine from an inline YAML configuration string. */
  static fromYaml(yaml: string): Engine
  /** Build an engine from a YAML configuration file path. */
  static fromPath(path: string): Engine
  /** Build an engine with no preconfigured sources. */
  static newEmpty(): Engine
  /**
   * Execute SQL and return a Promise that resolves with the
   * result encoded as Arrow IPC stream bytes (a Buffer in JS).
   * The Promise is rejected with the dbfy error message on
   * failure.
   *
   * napi-rs spawns the async fn on its own tokio runtime;
   * resolution / rejection lands back on the V8 main thread via
   * a ThreadsafeFunction.
   */
  query(sql: string): Promise<Buffer>
  /**
   * Synchronous variant — blocks the calling JS thread until the
   * query completes. Use only for short queries; prefer
   * {@link query} for anything else, especially in
   * request-handling paths.
   */
  querySync(sql: string): Buffer
  /**
   * Render the optimised logical plan + per-source pushdown
   * summary as a human-readable string.
   */
  explain(sql: string): Promise<string>
}
