// Umbrella header for the C ABI exposed by `dbfy-c`. Tracks
// `crates/dbfy-c/include/dbfy.h` (regenerated by cbindgen) — copy
// the upstream `dbfy.h` here on each release tag, or symlink during
// local development:
//
//   ln -sf ../../../../../crates/dbfy-c/include/dbfy.h \
//          bindings/swift/Sources/CDbfy/include/dbfy.h
//
// Then this umbrella includes it. Keeping the umbrella separate
// from the upstream header lets us add Swift-specific
// `__attribute__((swift_name(...)))` annotations later without
// touching the C generator.

#ifndef CDBFY_UMBRELLA_H
#define CDBFY_UMBRELLA_H

#include "dbfy.h"

#endif
