/* dbfy C bindings - auto-generated by cbindgen, do not edit. */

/* Forward declarations of the Arrow C Data Interface structs.
 * Callers that need to inspect the exported batches should also include
 * the canonical `arrow_c_data_interface.h` from their Arrow distribution. */
typedef struct ArrowSchema ArrowSchema;
typedef struct ArrowArray ArrowArray;

#ifndef DBFY_H
#define DBFY_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for an engine instance.
 */
typedef struct DbfyEngine DbfyEngine;

/**
 * Opaque handle for a query result holding one or more Arrow record batches.
 */
typedef struct DbfyResult DbfyResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the last error message recorded on the current thread, or NULL if
 * no error has occurred. The pointer remains valid until the next failing
 * call on the same thread.
 */
const char *dbfy_last_error(void);

/**
 * Build an engine from an inline YAML configuration string. Returns NULL on
 * failure (use [`dbfy_last_error`] to retrieve the message).
 */
struct DbfyEngine *dbfy_engine_new_from_yaml(const char *yaml);

/**
 * Build an engine from a YAML configuration file path.
 */
struct DbfyEngine *dbfy_engine_new_from_path(const char *path);

/**
 * Build an engine with no REST sources. Programmatic providers can be added
 * later from native Rust code.
 */
struct DbfyEngine *dbfy_engine_new_empty(void);

/**
 * Free an engine instance.
 */
void dbfy_engine_free(struct DbfyEngine *engine);

/**
 * Render the optimized logical plan as a heap-allocated C string. The caller
 * must release it with [`dbfy_string_free`]. Returns NULL on failure.
 */
char *dbfy_engine_explain(const struct DbfyEngine *engine, const char *sql);

/**
 * Free a string allocated by [`dbfy_engine_explain`].
 */
void dbfy_string_free(char *s);

/**
 * Execute a SQL query, returning a result handle on success. Returns 0 on
 * success and -1 on failure.
 */
int32_t dbfy_engine_query(const struct DbfyEngine *engine,
                          const char *sql,
                          struct DbfyResult **out_result);

/**
 * Number of record batches in a result, or 0 if `result` is NULL.
 */
uintptr_t dbfy_result_batch_count(const struct DbfyResult *result);

/**
 * Total number of rows across all batches in a result, or 0 if NULL.
 */
uintptr_t dbfy_result_row_count(const struct DbfyResult *result);

/**
 * Export the batch at `index` to caller-allocated Arrow C Data Interface
 * structures. The caller must call the `release` callback on each struct
 * after use. Returns 0 on success, -1 on failure.
 */
int32_t dbfy_result_export_batch(const struct DbfyResult *result,
                                 uintptr_t index,
                                 ArrowArray *out_array,
                                 ArrowSchema *out_schema);

/**
 * Free a query result.
 */
void dbfy_result_free(struct DbfyResult *result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DBFY_H */
