//! C bindings for the embedded dbfy federated SQL engine.
//!
//! The header `include/dbfy.h` is regenerated by `cbindgen` on every build.
//! All functions return either an opaque pointer (NULL on failure) or a
//! status code (`0` on success, `-1` on failure). On failure, call
//! [`dbfy_last_error`] from the same thread to retrieve the message.

#![allow(clippy::missing_safety_doc)]

use std::cell::RefCell;
use std::ffi::{CStr, CString, c_char};
use std::ptr;
use std::sync::Arc;

use arrow_array::Array;
use arrow_array::RecordBatch;
use arrow_array::StructArray;
use arrow_array::ffi::{FFI_ArrowArray, FFI_ArrowSchema, to_ffi};
use dbfy_config::Config;
use dbfy_frontend_datafusion::Engine;
use tokio::runtime::Runtime;

thread_local! {
    static LAST_ERROR: RefCell<Option<CString>> = const { RefCell::new(None) };
}

fn set_last_error(message: impl std::fmt::Display) {
    let owned = message.to_string().replace('\0', "?");
    let cstring = CString::new(owned).unwrap_or_else(|_| CString::new("error").unwrap());
    LAST_ERROR.with(|cell| *cell.borrow_mut() = Some(cstring));
}

/// Returns the last error message recorded on the current thread, or NULL if
/// no error has occurred. The pointer remains valid until the next failing
/// call on the same thread.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_last_error() -> *const c_char {
    LAST_ERROR.with(|cell| {
        cell.borrow()
            .as_ref()
            .map(|s| s.as_ptr())
            .unwrap_or(ptr::null())
    })
}

/// Opaque handle for an engine instance.
pub struct DbfyEngine {
    inner: Engine,
    runtime: Arc<Runtime>,
}

/// Opaque handle for a query result holding one or more Arrow record batches.
pub struct DbfyResult {
    batches: Vec<RecordBatch>,
}

/// Build an engine from an inline YAML configuration string. Returns NULL on
/// failure (use [`dbfy_last_error`] to retrieve the message).
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_new_from_yaml(yaml: *const c_char) -> *mut DbfyEngine {
    if yaml.is_null() {
        set_last_error("yaml pointer is null");
        return ptr::null_mut();
    }
    let yaml_str = match unsafe { CStr::from_ptr(yaml) }.to_str() {
        Ok(s) => s,
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };

    let config = match Config::from_yaml_str(yaml_str) {
        Ok(c) => c,
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };
    build_engine(Engine::from_config(config))
}

/// Build an engine from a YAML configuration file path.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_new_from_path(path: *const c_char) -> *mut DbfyEngine {
    if path.is_null() {
        set_last_error("path pointer is null");
        return ptr::null_mut();
    }
    let path_str = match unsafe { CStr::from_ptr(path) }.to_str() {
        Ok(s) => s,
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };
    build_engine(Engine::from_config_file(path_str))
}

/// Build an engine with no REST sources. Programmatic providers can be added
/// later from native Rust code.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_new_empty() -> *mut DbfyEngine {
    let runtime = match Runtime::new() {
        Ok(r) => Arc::new(r),
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };
    Box::into_raw(Box::new(DbfyEngine {
        inner: Engine::default(),
        runtime,
    }))
}

fn build_engine(
    engine: Result<Engine, dbfy_frontend_datafusion::EngineError>,
) -> *mut DbfyEngine {
    let engine = match engine {
        Ok(e) => e,
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };
    let runtime = match Runtime::new() {
        Ok(r) => Arc::new(r),
        Err(err) => {
            set_last_error(err);
            return ptr::null_mut();
        }
    };
    Box::into_raw(Box::new(DbfyEngine {
        inner: engine,
        runtime,
    }))
}

/// Free an engine instance.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_free(engine: *mut DbfyEngine) {
    if !engine.is_null() {
        let _ = unsafe { Box::from_raw(engine) };
    }
}

/// Render the optimized logical plan as a heap-allocated C string. The caller
/// must release it with [`dbfy_string_free`]. Returns NULL on failure.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_explain(
    engine: *const DbfyEngine,
    sql: *const c_char,
) -> *mut c_char {
    let Some((engine, sql)) = checked_engine_sql(engine, sql) else {
        return ptr::null_mut();
    };
    match engine.runtime.block_on(engine.inner.explain(sql)) {
        Ok(s) => match CString::new(s) {
            Ok(c) => c.into_raw(),
            Err(err) => {
                set_last_error(err);
                ptr::null_mut()
            }
        },
        Err(err) => {
            set_last_error(err);
            ptr::null_mut()
        }
    }
}

/// Free a string allocated by [`dbfy_engine_explain`].
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_string_free(s: *mut c_char) {
    if !s.is_null() {
        let _ = unsafe { CString::from_raw(s) };
    }
}

/// Execute a SQL query, returning a result handle on success. Returns 0 on
/// success and -1 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_engine_query(
    engine: *const DbfyEngine,
    sql: *const c_char,
    out_result: *mut *mut DbfyResult,
) -> i32 {
    if out_result.is_null() {
        set_last_error("out_result pointer is null");
        return -1;
    }
    let Some((engine, sql)) = checked_engine_sql(engine, sql) else {
        return -1;
    };
    match engine.runtime.block_on(engine.inner.query(sql)) {
        Ok(batches) => {
            let boxed = Box::new(DbfyResult { batches });
            unsafe { *out_result = Box::into_raw(boxed) };
            0
        }
        Err(err) => {
            set_last_error(err);
            -1
        }
    }
}

/// Number of record batches in a result, or 0 if `result` is NULL.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_result_batch_count(result: *const DbfyResult) -> usize {
    if result.is_null() {
        return 0;
    }
    unsafe { (*result).batches.len() }
}

/// Total number of rows across all batches in a result, or 0 if NULL.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_result_row_count(result: *const DbfyResult) -> usize {
    if result.is_null() {
        return 0;
    }
    unsafe { &*result }
        .batches
        .iter()
        .map(|b| b.num_rows())
        .sum()
}

/// Export the batch at `index` to caller-allocated Arrow C Data Interface
/// structures. The caller must call the `release` callback on each struct
/// after use. Returns 0 on success, -1 on failure.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_result_export_batch(
    result: *const DbfyResult,
    index: usize,
    out_array: *mut FFI_ArrowArray,
    out_schema: *mut FFI_ArrowSchema,
) -> i32 {
    if result.is_null() || out_array.is_null() || out_schema.is_null() {
        set_last_error("null pointer");
        return -1;
    }
    let result = unsafe { &*result };
    let Some(batch) = result.batches.get(index) else {
        set_last_error(format!(
            "batch index {} out of range (count={})",
            index,
            result.batches.len()
        ));
        return -1;
    };
    let struct_array: StructArray = batch.clone().into();
    let array_data = struct_array.into_data();
    match to_ffi(&array_data) {
        Ok((arr, sch)) => {
            unsafe {
                ptr::write(out_array, arr);
                ptr::write(out_schema, sch);
            }
            0
        }
        Err(err) => {
            set_last_error(err);
            -1
        }
    }
}

/// Free a query result.
#[unsafe(no_mangle)]
pub extern "C" fn dbfy_result_free(result: *mut DbfyResult) {
    if !result.is_null() {
        let _ = unsafe { Box::from_raw(result) };
    }
}

fn checked_engine_sql<'a>(
    engine: *const DbfyEngine,
    sql: *const c_char,
) -> Option<(&'a DbfyEngine, &'a str)> {
    if engine.is_null() || sql.is_null() {
        set_last_error("null pointer");
        return None;
    }
    let sql_str = match unsafe { CStr::from_ptr(sql) }.to_str() {
        Ok(s) => s,
        Err(err) => {
            set_last_error(err);
            return None;
        }
    };
    Some((unsafe { &*engine }, sql_str))
}
