//! Emits a DuckDB SQL script that materialises every table in a dbfy
//! YAML config as a `CREATE OR REPLACE VIEW` over the appropriate
//! `dbfy_rest()` or `dbfy_rows_file()` table function. Acts as a
//! today-shippable substitute for `ATTACH 'config.yaml' (TYPE dbfy)`,
//! which is blocked upstream until `duckdb-rs` exposes the
//! `StorageExtension` C API. Once that lands the attach surface can
//! switch to a real catalog provider; the SQL contract stays identical.

use std::collections::BTreeMap;
use std::path::PathBuf;

use anyhow::{Context, Result, anyhow};
use dbfy_config::{
    AuthConfig, ColumnConfig, Config, IndexedColumnConfig, PaginationConfig, ParserConfig,
    PushdownConfig, RestSourceConfig, RestTableConfig, RowsFileTableConfig, SourceConfig,
};
use serde::Serialize;

#[derive(Debug, Clone)]
pub struct AttachOpts {
    /// DuckDB schema in which the views are created (e.g. `api`).
    pub schema: String,
    /// If set, the script begins with `LOAD '<path>';` so the user can
    /// run the file standalone (`duckdb < attach.sql`) without needing
    /// to remember the extension path.
    pub extension: Option<PathBuf>,
    /// Use `CREATE VIEW` instead of `CREATE OR REPLACE VIEW`. Useful in
    /// CI where you want the script to fail loudly if a view already
    /// exists with a different definition.
    pub strict: bool,
}

impl Default for AttachOpts {
    fn default() -> Self {
        Self {
            schema: "dbfy".to_string(),
            extension: None,
            strict: false,
        }
    }
}

pub fn emit_attach_sql(config: &Config, opts: &AttachOpts) -> Result<String> {
    if opts.schema.trim().is_empty() {
        return Err(anyhow!("schema must not be empty"));
    }
    let mut out = String::new();
    out.push_str("-- Generated by `dbfy duckdb-attach`. Pipe this into duckdb:\n");
    out.push_str("--   duckdb mydb.duckdb < attach.sql\n");
    out.push('\n');
    if let Some(ext) = &opts.extension {
        out.push_str(&format!(
            "LOAD '{}';\n\n",
            sql_string_escape(ext.to_str().context("extension path is not valid UTF-8")?)
        ));
    }
    out.push_str(&format!(
        "CREATE SCHEMA IF NOT EXISTS \"{}\";\n\n",
        sql_ident_escape(&opts.schema)
    ));

    let create_kw = if opts.strict {
        "CREATE VIEW"
    } else {
        "CREATE OR REPLACE VIEW"
    };

    for (source_name, source) in &config.sources {
        match source {
            SourceConfig::Rest(rest) => {
                emit_rest_views(&mut out, source_name, rest, &opts.schema, create_kw)?;
            }
            SourceConfig::RowsFile(rf) => {
                emit_rows_file_views(&mut out, source_name, rf, &opts.schema, create_kw)?;
            }
            // The DuckDB extension exposes only `dbfy_rest()` and
            // `dbfy_rows_file()` table functions today; parquet /
            // excel / graphql / postgres sources can be queried
            // through the standalone CLI but won't show up under
            // `dbfy duckdb-attach` until corresponding DuckDB
            // table-function wrappers are added.
            SourceConfig::Parquet(_)
            | SourceConfig::Excel(_)
            | SourceConfig::Graphql(_)
            | SourceConfig::Postgres(_) => {
                out.push_str(&format!(
                    "-- source `{source_name}` ({}) skipped — not yet wired into the DuckDB extension\n\n",
                    source_kind_name(source)
                ));
            }
        }
    }
    Ok(out)
}

fn source_kind_name(source: &SourceConfig) -> &'static str {
    match source {
        SourceConfig::Rest(_) => "rest",
        SourceConfig::RowsFile(_) => "rows_file",
        SourceConfig::Parquet(_) => "parquet",
        SourceConfig::Excel(_) => "excel",
        SourceConfig::Graphql(_) => "graphql",
        SourceConfig::Postgres(_) => "postgres",
    }
}

fn emit_rest_views(
    out: &mut String,
    source_name: &str,
    rest: &RestSourceConfig,
    schema: &str,
    create_kw: &str,
) -> Result<()> {
    out.push_str(&format!(
        "-- source `{source_name}` (REST {})\n",
        rest.base_url
    ));
    for (table_name, table_cfg) in &rest.tables {
        let url = join_url(&rest.base_url, &table_cfg.endpoint.path);
        let yaml = serde_yaml::to_string(&RestTableExtensionConfig::from_parts(rest, table_cfg))
            .context("serialising per-table REST config")?;
        out.push_str(&format!(
            "{create_kw} \"{schema}\".\"{table}\" AS\n  SELECT * FROM dbfy_rest(\n    '{url}',\n    config := '{cfg}'\n  );\n\n",
            schema = sql_ident_escape(schema),
            table = sql_ident_escape(table_name),
            url = sql_string_escape(&url),
            cfg = sql_string_escape(&yaml),
        ));
    }
    Ok(())
}

fn emit_rows_file_views(
    out: &mut String,
    source_name: &str,
    rf: &dbfy_config::RowsFileSourceConfig,
    schema: &str,
    create_kw: &str,
) -> Result<()> {
    out.push_str(&format!("-- source `{source_name}` (rows_file)\n"));
    for (table_name, table_cfg) in &rf.tables {
        let target = table_cfg
            .path
            .clone()
            .or_else(|| table_cfg.glob.clone())
            .ok_or_else(|| anyhow!("rows_file table `{table_name}` has neither path nor glob"))?;
        let yaml = serde_yaml::to_string(&RowsFileTableExtensionConfig::from_parts(table_cfg))
            .context("serialising per-table rows_file config")?;
        out.push_str(&format!(
            "{create_kw} \"{schema}\".\"{table}\" AS\n  SELECT * FROM dbfy_rows_file(\n    '{target}',\n    config := '{cfg}'\n  );\n\n",
            schema = sql_ident_escape(schema),
            table = sql_ident_escape(table_name),
            target = sql_string_escape(&target),
            cfg = sql_string_escape(&yaml),
        ));
    }
    Ok(())
}

/// YAML schema accepted by `dbfy_rest()`'s `config :=` argument. Built from
/// a `(RestSourceConfig, RestTableConfig)` pair: source contributes auth,
/// table contributes the rest.
#[derive(Debug, Serialize)]
struct RestTableExtensionConfig {
    root: String,
    columns: BTreeMap<String, ColumnConfig>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pagination: Option<PaginationConfig>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pushdown: Option<PushdownConfig>,
    #[serde(skip_serializing_if = "Option::is_none")]
    auth: Option<AuthConfig>,
}

impl RestTableExtensionConfig {
    fn from_parts(source: &RestSourceConfig, table: &RestTableConfig) -> Self {
        Self {
            root: table.root.clone(),
            columns: table.columns.clone(),
            pagination: table.pagination.clone(),
            pushdown: table.pushdown.clone(),
            auth: source.auth.clone(),
        }
    }
}

/// YAML schema accepted by `dbfy_rows_file()`'s `config :=` argument.
#[derive(Debug, Serialize)]
struct RowsFileTableExtensionConfig {
    parser: ParserConfig,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    indexed_columns: Vec<IndexedColumnConfig>,
    #[serde(skip_serializing_if = "Option::is_none")]
    chunk_rows: Option<usize>,
}

impl RowsFileTableExtensionConfig {
    fn from_parts(table: &RowsFileTableConfig) -> Self {
        Self {
            parser: table.parser.clone(),
            indexed_columns: table.indexed_columns.clone(),
            chunk_rows: table.chunk_rows,
        }
    }
}

fn join_url(base_url: &str, endpoint_path: &str) -> String {
    let base = base_url.trim_end_matches('/');
    let path = if endpoint_path.starts_with('/') {
        endpoint_path.to_string()
    } else {
        format!("/{endpoint_path}")
    };
    format!("{base}{path}")
}

/// SQL string-literal escape: `'` → `''`. The whole literal is wrapped in
/// single quotes by the caller.
fn sql_string_escape(s: &str) -> String {
    s.replace('\'', "''")
}

/// SQL identifier escape for double-quoted identifiers: `"` → `""`.
fn sql_ident_escape(s: &str) -> String {
    s.replace('"', "\"\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use dbfy_config::{
        CellTypeConfig, ColumnConfig, DataType, EndpointConfig, HttpMethod, JsonlColumnConfig,
        ParserConfig, RestTableConfig, RowsFileSourceConfig, RowsFileTableConfig,
    };

    fn empty_rest_table() -> RestTableConfig {
        RestTableConfig {
            endpoint: EndpointConfig {
                method: HttpMethod::Get,
                path: "/things".to_string(),
            },
            root: "$.data[*]".to_string(),
            primary_key: None,
            include_raw_json: false,
            raw_column: "_raw".to_string(),
            columns: BTreeMap::from([(
                "id".to_string(),
                ColumnConfig {
                    path: "$.id".to_string(),
                    r#type: DataType::Int64,
                },
            )]),
            pagination: None,
            pushdown: None,
        }
    }

    #[test]
    fn emits_schema_and_view_for_rest_source() {
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        config.sources.insert(
            "crm".to_string(),
            SourceConfig::Rest(RestSourceConfig {
                base_url: "https://api.example.com".to_string(),
                auth: None,
                runtime: None,
                tables: BTreeMap::from([("customers".to_string(), empty_rest_table())]),
            }),
        );
        let sql = emit_attach_sql(
            &config,
            &AttachOpts {
                schema: "api".to_string(),
                ..AttachOpts::default()
            },
        )
        .unwrap();

        assert!(sql.contains("CREATE SCHEMA IF NOT EXISTS \"api\";"));
        assert!(sql.contains("CREATE OR REPLACE VIEW \"api\".\"customers\""));
        assert!(sql.contains("dbfy_rest("));
        assert!(sql.contains("https://api.example.com/things"));
        // YAML body should round-trip through the dbfy_rest config schema.
        assert!(sql.contains("root: $.data[*]"));
    }

    #[test]
    fn emits_view_for_rows_file_source() {
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        config.sources.insert(
            "logs".to_string(),
            SourceConfig::RowsFile(RowsFileSourceConfig {
                tables: BTreeMap::from([(
                    "events".to_string(),
                    RowsFileTableConfig {
                        path: Some("/var/log/events.jsonl".to_string()),
                        glob: None,
                        parser: ParserConfig::Jsonl {
                            columns: vec![JsonlColumnConfig {
                                name: "id".to_string(),
                                path: "$.id".to_string(),
                                r#type: CellTypeConfig::Int64,
                            }],
                        },
                        indexed_columns: vec![],
                        chunk_rows: Some(2048),
                    },
                )]),
            }),
        );
        let sql = emit_attach_sql(
            &config,
            &AttachOpts {
                schema: "logs".to_string(),
                ..AttachOpts::default()
            },
        )
        .unwrap();

        assert!(sql.contains("CREATE OR REPLACE VIEW \"logs\".\"events\""));
        assert!(sql.contains("dbfy_rows_file("));
        assert!(sql.contains("'/var/log/events.jsonl'"));
        assert!(sql.contains("chunk_rows: 2048"));
    }

    #[test]
    fn extension_path_is_emitted_as_load_statement() {
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        config.sources.insert(
            "x".to_string(),
            SourceConfig::Rest(RestSourceConfig {
                base_url: "http://example.com".to_string(),
                auth: None,
                runtime: None,
                tables: BTreeMap::from([("t".to_string(), empty_rest_table())]),
            }),
        );
        let sql = emit_attach_sql(
            &config,
            &AttachOpts {
                schema: "x".to_string(),
                extension: Some("/opt/dbfy.duckdb_extension".into()),
                strict: false,
            },
        )
        .unwrap();

        assert!(
            sql.contains("LOAD '/opt/dbfy.duckdb_extension';"),
            "missing LOAD: {sql}"
        );
    }

    #[test]
    fn single_quotes_in_url_are_escaped() {
        // Pathological URL with a single quote in the query string.
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        let mut table = empty_rest_table();
        table.endpoint.path = "/items?q=O'Brien".to_string();
        config.sources.insert(
            "x".to_string(),
            SourceConfig::Rest(RestSourceConfig {
                base_url: "http://example.com".to_string(),
                auth: None,
                runtime: None,
                tables: BTreeMap::from([("t".to_string(), table)]),
            }),
        );
        let sql = emit_attach_sql(&config, &AttachOpts::default()).unwrap();
        assert!(
            sql.contains("'http://example.com/items?q=O''Brien'"),
            "{sql}"
        );
    }

    #[test]
    fn strict_mode_uses_create_view_without_or_replace() {
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        config.sources.insert(
            "x".to_string(),
            SourceConfig::Rest(RestSourceConfig {
                base_url: "http://example.com".to_string(),
                auth: None,
                runtime: None,
                tables: BTreeMap::from([("t".to_string(), empty_rest_table())]),
            }),
        );
        let sql = emit_attach_sql(
            &config,
            &AttachOpts {
                schema: "x".to_string(),
                strict: true,
                ..AttachOpts::default()
            },
        )
        .unwrap();
        assert!(sql.contains("CREATE VIEW \"x\""));
        assert!(!sql.contains("OR REPLACE"));
    }

    #[test]
    fn empty_schema_is_rejected() {
        let mut config = Config {
            version: 1,
            sources: BTreeMap::new(),
        };
        config.sources.insert(
            "x".to_string(),
            SourceConfig::Rest(RestSourceConfig {
                base_url: "http://example.com".to_string(),
                auth: None,
                runtime: None,
                tables: BTreeMap::from([("t".to_string(), empty_rest_table())]),
            }),
        );
        let err = emit_attach_sql(
            &config,
            &AttachOpts {
                schema: "  ".to_string(),
                ..AttachOpts::default()
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("schema must not be empty"));
    }
}
